POST {{url}}/gettoken
Content-Type: application/x-www-form-urlencoded

user={{username}}&pass={{password}}

> {%
client.global.set("token", response.body.token);
 %}
###
POST {{url}}/userinfo
Content-Type: application/x-www-form-urlencoded

token={{token}}
###
GET {{url}}/rasp
###
GET {{url}}/last?page=1&quantity=50
###
POST {{url}}/info
Content-Type: application/x-www-form-urlencoded

id=2436
###
POST {{url}}/playlist
Content-Type: application/x-www-form-urlencoded

id=1234
###
GET {{url}}/genres
###
POST {{url}}/search
Content-Type: application/x-www-form-urlencoded

year=2019
###
POST {{url}}/favorites
Content-Type: application/x-www-form-urlencoded

token={{token}}
###
POST {{url}}/addfavorites
Content-Type: application/x-www-form-urlencoded

token={{token}}&id=1235
###
POST {{url}}/delfavorites
Content-Type: application/x-www-form-urlencoded

token={{token}}&id=1234
###
